"""add tenant FK to mixin

Revision ID: 57c70bf99f98
Revises: 5dddd76f29f3
Create Date: 2026-03-01 21:08:20.438153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c70bf99f98'
down_revision: Union[str, None] = '5dddd76f29f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'academic_years', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'campuses', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'relationships', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint(None, 'campuses', type_='foreignkey')
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    # ### end Alembic commands ###
